import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppProviders from "@/controls/AppProviders";
import Header from "@/components/base/Header";
import AppUtilities from "@/controls/AppUtilities";
import Main from "../components/base/Main";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="overscroll-none">
                <AppProviders>
                    <Header Logo={<span>KM-WebDev</span>} />
                    <Main>{children}</Main>
                </AppProviders>
                <AppUtilities />
            </body>
        </html>
    );
}
