import type { Metadata } from "next";
import "./globals.css";
import AppProviders from "@/controls/AppProviders";
import Header from "@/components/base/Header";
import AppUtilities from "@/controls/AppUtilities";
import Main from "../components/base/Main";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

import { Inter } from "next/font/google";
import { Outfit } from "next/font/google";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const outfit = Outfit({ subsets: ["latin"], variable: "--font-outfit" });

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${inter.variable} ${outfit.variable}`}>
            <body className="overscroll-none">
                <AppProviders>
                    <Header Logo={<span>KM-WebDev</span>} />
                    <Main>{children}</Main>
                </AppProviders>
                <AppUtilities />
            </body>
        </html>
    );
}
